### ISSUE TITLE
How to authenticate ?

### ISSUE THREAD

**Issue by adalidda** [yeasy/docker-mongo-connector#1]
Dear Yeasy,

I use replicaset with authentication as below:
MONGO_URL=mongodb://user:password@ip:port1/databasename?authSource=admin 
MONGO_OPLOG_URL=mongodb://useroplog:passwordoplog@ip:port1,ip:port2,ip:port3/local?authSource=admin \

When I type:
docker run --restart=always --name mongoconnector -d --link=replicamaster:mongo --link=elasticsearch:elasticsearch yeasy/mongo-connector

I get message Waiting for Mongod node to assume primary status...

but nothing happen

I think because I didn't authenticate with docker command. How to authenticate with your docker image yeasy/mongo-connector ?

Thank You
Kosona Chriv

**Comment by yeasy** [comment]
Hi Kosona
I guess you need to modify the startup.sh file, to read the authentication parameters from external.

**Comment by viztastic** [comment]
Do you have any recommendations on how to do that securely @yeasy ?
