### ISSUE TITLE
Write logs to syslog rather than file

### ISSUE THREAD

**Issue by em0ney** [yeasy/docker-mongo-connector#7]
Hi there,

I'm having issues with this repo.  Where the container fails, the logs just show that the logs are being written to a file on the container.  Can we change this up to write to syslog instead?  Means we can get log details from failed containers easily.

Any thoughts? Objections?

**Comment by yeasy** [comment]
Seems it's due to the container setting, non related to this repo, which just build up the image.

**Comment by em0ney** [comment]
I worked it out.  Add --syslog to the mongo-connector command
